# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

contact_links:
  - name: Ask a question
    url: https://github.com/orgs/openbao/discussions
    about: For increased visibility, please post questions with `k8s` in subject
