# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: openbao-agent-injector-cfg
  labels:
    app.kubernetes.io/name: openbao-injector
    app.kubernetes.io/instance: openbao
webhooks:
  - name: openbao.openbao.org
    sideEffects: None
    admissionReviewVersions:
      - "v1"
      - "v1beta1"
    clientConfig:
      service:
        name: openbao-agent-injector-svc
        path: "/mutate"
        namespace: "openbao"
      caBundle: ""
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["deployments", "jobs", "pods", "statefulsets"]
    namespaceSelector: {}
    objectSelector:
      matchExpressions:
      - key: app.kubernetes.io/name
        operator: NotIn
        values: ["openbao-injector"]
    failurePolicy: Ignore
