# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: v1
kind: Service
metadata:
  name: openbao-agent-injector-svc
  namespace: openbao
  labels:
    app.kubernetes.io/name: openbao-injector
    app.kubernetes.io/instance: openbao
spec:
  ports:
  - name: https
    port: 443
    targetPort: 8080
  selector:
    app.kubernetes.io/name: openbao-injector
    app.kubernetes.io/instance: openbao
