# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openbao-injector
  labels:
    app.kubernetes.io/name: openbao-injector
    app.kubernetes.io/instance: openbao
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openbao-injector-clusterrole
  labels:
    app.kubernetes.io/name: openbao-injector
    app.kubernetes.io/instance: openbao
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: 
    - "get"
    - "list"
    - "watch"
    - "patch"
- apiGroups: [""]
  resources: ["nodes"]
  verbs:
    - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openbao-injector-binding
  labels:
    app.kubernetes.io/name: openbao-injector
    app.kubernetes.io/instance: openbao
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openbao-injector-clusterrole
subjects:
- kind: ServiceAccount
  name: openbao-injector
  namespace: openbao
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openbao-injector-role
  labels:
    app.kubernetes.io/name: openbao-injector
    app.kubernetes.io/instance: openbao
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: 
    - "create"
    - "get"
    - "watch"
    - "list"
    - "update"
- apiGroups: [""]
  resources: ["pods"]
  verbs:
    - "get"
    - "patch"
    - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openbao-injector-rolebinding
  labels:
    app.kubernetes.io/name: openbao-injector
    app.kubernetes.io/instance: openbao
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openbao-injector-role
subjects:
- kind: ServiceAccount
  name: openbao-injector
  namespace: openbao
